stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  CI_REGISTRY: "registry.gitlab.com"
  CI_REGISTRY_IMAGE: "$CI_REGISTRY/finance8645134/billing_software_be"
  CI_REGISTRY_USER: "$CI_JOB_USER"
  CI_REGISTRY_PASSWORD: "$CI_JOB_TOKEN"

build_image:
  stage: build
  image: maven:3.8.5-openjdk-17
  script:
    - mvn clean install
  artifacts:
    paths:
      - "target/billing_software-0.0.1-SNAPSHOT.jar"
    expire_in: 1 day  # Set expiration period for artifacts

docker_operations:
  stage: deploy
  image: docker:20.10.8
  services:
    - docker:dind
  script:
    - docker --version  # Verify Docker is available
    - echo "$CI_REGISTRY_PASSWORD" > password.txt
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"